### ISSUE TITLE
Find clusters based on scRNA-seq and scATAC-seq co-embedding

### ISSUE THREAD

**Issue by PeggySze** [KChen-lab/bindSC#2]
Hi, Thanks for developing such a great tool. I have used it to integrate my scRNA-seq and scATAC-seq datasets and project cells from two modalites in co-embedding spaces. The co-embedding is great and matches biological function, so I'd like to use this co-embedding for my scATAC-seq downstream analysis. It's possible to find clusters based on this co-embedding?

**Comment by jinzhuangdou** [comment]
Current bindSC has no module to perform joint clustering in co-embeddings. You can put the co-embeddings into Seurat: obj[["bindsc]]<-createdimreducobject(embeddings=bindsc) and use Seurat function for downstream analysis.
