### ISSUE TITLE
bindSC for integrating multiple CITE-seq samples

### ISSUE THREAD

**Issue by jarchana09** [KChen-lab/bindSC#3]
Hi, thank you for developing this very useful package.
Request you to kindly suggest if you have any vignettes/guidance for integrating multiple CITE-seq samples, where the mRNA and protein (TotalSeq A) have been sequenced for each of set of samples. 
Thank you so much.

Sincerely,
Archana

**Comment by jinzhuangdou** [comment]
That is a good question. Unfortunately, bindSC is not the best way to integrate multiple samples measured with CITE-seq. 
Have you tried CCA on each modality and then use WNN to integrate different modality?
