### ISSUE TITLE
How to obtain feature pairs

### ISSUE THREAD

**Issue by sshen82** [KChen-lab/bindSC#4]
Hi,
Thank you for this great package! I have a question about how to get the feature pairs like what is illustrated in additional Figure 5 in your paper? I don't see this in the tutorials but I am quite curious about how to perform that.

![1655216893238](https://user-images.githubusercontent.com/29969832/173602531-4dba354a-7ce9-4eb7-9c65-5765cbf63ab6.png)

Thanks,
Siqi Shen

**Comment by jinzhuangdou** [comment]
Hi, you can plot this figure using ArchR tool (https://www.archrproject.com/bookdown/peak2genelinkage-with-archr.html). Current bindSC has no module for this plot.

**Comment by sshen82** [comment]
Thanks for this, but I am asking how to obtain the link between peaks and genes? Based on correlation?

**Comment by jinzhuangdou** [comment]
For bindSC, you can derive an imputed matrix Z for cells from atac.  You can calculate gene-peak pair using correlation cor(Z, Y).

**Comment by sshen82** [comment]
Ah, get it. Thank you for your help!
